### ISSUE TITLE
Inability to parse 

### ISSUE THREAD

**Issue by viper2846** [sdaschner/jaxrs-analyzer#105]
I am using the jaxrs-analyzer v .10 standalone against my code. (using Windows 7 box with jdk 8 installed).  Every time I run it against my code I get this:
```
java -jar c:\users\xxx\jaxrs-analyzer.jar -X -n "My Project" build/classes/main
Exception in thread "main" java.lang.ArrayStoreException
        at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:736)
        at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:543)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:367)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:298)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:132)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:84)
        at java.lang.Class.getAnnotationCache(Class.java:2539)
        at java.lang.Class.getAnnotations(Class.java:2229)
        at com.sebastian_daschner.jaxrs_analyzer.model.JavaUtils.isAnnotationPresent(JavaUtils.java:75)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.isJAXRSRootResource(ProjectAnalyzer.java:112)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer$$Lambda$109.000000001195F650.test(Unknown Sour
ce)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:185)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1551)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:523)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:513)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:162)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:185)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:245)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:429)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:91)
        at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:64)
        at com.sebastian_daschner.jaxrs_analyzer.Main.main(Main.java:97)
```

Even though I have -X I don't see anything more than what is shown here.  I put a sample annotated java file in my code base to see if it would pick that up.  It didn't.   I created a totally separate project that has the sample annotated java file and it works.  My project builds fine as a gradle multiproject project.  I am trying the jaxrs-analyzer against the web portion (one of the subprojects) .

Any thoughts on how to proceed?

**Comment by sdaschner** [comment]
Ok, that one is new. Can you please try with the latest `0.12` version?
