### ISSUE TITLE
Cli tools.jar does not exist

### ISSUE THREAD

**Issue by waraz** [sdaschner/jaxrs-analyzer#152]
Hi, firstly its a great useful application you have coming from your thesis. Nice handy tool for all Java web developers.

I'm trying out the analyzer to generate a swagger doc. However, had issues with the running jar failing to locate a tools.jar from the JRE. 

Using v0.15 jar from download page.

$ java -jar jaxrs-analyzer.jar -b swagger -cp vmsrjet/target/classes tools.jar
Exception in thread "main" java.lang.IllegalArgumentException: The location 'C:\Program Files\Java\jre1.8.0_162\..\lib\tools.jar' does not exist!
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.addToClassPool(ProjectAnalyzer.java:148)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.<init>(ProjectAnalyzer.java:78)
        at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:69)
        at com.sebastian_daschner.jaxrs_analyzer.Main.main(Main.java:94)

Tried a bunch but somehow it isn't able to pass. Could you help with running it especially in the windows environment. I used the normal cmd.exe as well as GitBash shell on win 10.

I'm using the standalone cli as I had issues with building the project cause Maven pom.xml uses the 1.7sdk. 

Error injecting: org.eclipse.jetty.maven.plugin.JettyRunMojojava.lang.TypeNotPresentException: Type org.eclipse.jetty.maven.plugin.JettyRunMojo not present

Also, is it possible to build my project with 1.7 while using 1.8 for jaxrs-analyzer?

**Comment by torniketar** [comment]
i have the same problem

**Comment by sdaschner** [comment]
Can you please try again with the `0.17` version of the analyzer?
