### ISSUE TITLE
Jax-RS Analyze Static Property Error

### ISSUE THREAD

**Issue by hawkbase4git** [sdaschner/jaxrs-analyzer#189]
I am using version 0.17 with Swagger as the backend. I am getting Jax-Rs Analyzer "Could not access the Static Property" error for various modules.

**Comment by thebluemountain** [comment]
i have been trying to use the 0.17 version with markdown backend in a maven project.
encountered same issue.
adding the -X flag to get more messages, the issue is encountered in the analysis class.
...
	at java.lang.Class.forName(Class.java:264)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.InstructionBuilder.getStaticValue(InstructionBuilder.java:295)
...

looking at the source, i see:
...
            **// needs to load same class instance in Maven plugin, not from extended classloader**
            final Class<?> clazz = Class.forName(containingClass.replace('/', '.'));
            field = clazz.getDeclaredField(name);
...
not sure what it means though
