### ISSUE TITLE
NPE on analyzing method

### ISSUE THREAD

**Issue by sg-ad** [sdaschner/jaxrs-analyzer#23]
Hi,

I'm getting a lot of NullPointerException errors when analyzing our code.  Running with -X I can see errors like this:
```
[ERROR] Could not analyze the method: javassist.CtMethod@a0629d5c[public abstract partialUpdateCompanyMembership (Ljava/lang/String;Ljava/lang/Str
ing;Lcom/fasterxml/jackson/databind/JsonNode;)Lc/a/a/a/v/v/UserCompanyRelWS;]
[DEBUG] java.lang.NullPointerException
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.ByteCodeCollector.initializeBuilders(ByteCodeCollector.java:92)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.ByteCodeCollector.buildInstructions(ByteCodeCollector.java:59)
```

One thing of interest is that the annotations are defined on an interface so that implementations don't have to repeat them.  I wonder if that could explain why the `methodInfo.getCodeAttribute()` returns a  `null`?

Our build also produces some model classes into one module, and service classes into another.  How can I tell jaxrs-analyzer that it should look into _two_ directories for classes?  Something like this:
```
api/target/classes/<model>
service/target/classes/<services>
```

Finally, I get a `StackOverflowError` shortly after, but I'd like to first figure out the problems above as it might be a side effect.

Thanks!

**Comment by sdaschner** [comment]
Hi, this was fixed in the `0.6` version which I published yesterday.

So you currently include the Maven plugin in both modules? This means you get two results containing each content respectively?
You can specify several "class analyzing paths" when using the CLI of the https://github.com/sdaschner/jaxrs-analyzer (see the documentation at the bottom).

Do you still get the `StackOverflowError` after updating?

**Comment by sg-ad** [comment]
Hi, thanks for the quick reply!

I'm using latest, which is 0.6.  From the logs:
```
[DEBUG] Configuring mojo 'com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.6:analyze-jaxrs' with basic configurator -->
[DEBUG]   (f) backend = asciidoc
[DEBUG]   (f) buildDirectory = <...>/api/target
[DEBUG]   (f) deployedDomain = example.com
[DEBUG]   (f) outputDirectory = <...>/api/target/classes
[DEBUG]   (f) project = MavenProject: <...> @ <...>/api/pom.xm
[DEBUG] -- end configuration --
```
I'll try out the command line to specify several paths.

**Comment by sdaschner** [comment]
I see. Could you please provide more information, how this `partialUpdateCompanyMembership` method definition looks like and where it is called? It is perfectly fine to anonymize class and method names, btw.

This `methodInfo.getCodeAttribute` is called to get the bytecode information of a method; however the execution of that functionality _shouldn't_ be called on native or abstract methods, but apparently there is some special case missing...

**Comment by sg-ad** [comment]
Here's a snippet of that class:

``` java
@Path("/account/")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public interface AccountApi {
// ...
	@PATCH
	@Path("/companies/{companyId}/memberships/{userId}")
	UserCompanyRelWS partialUpdateCompanyMembership(
			@PathParam("companyId") String companyId,
			@PathParam("userId") String userId,
			JsonNode userCompanyRelWS
	);
```
The implementation has a few additional annotations that are probably not at play here, but just in case:

``` java
@Slf4j
@RestService
public class AccountApiImpl implements AccountApi {
// ...
	@Override
	@Transactional
	@PreAuthorize("@<role>")
	public UserCompanyRelWS partialUpdateCompanyMembership(String companyId, String userId, JsonNode userCompanyRelWS) {
```

The `@RestService` annotation is a convenience basically identifying the `AccountApiImpl` class as a Spring component.

Thanks!

**Comment by sdaschner** [comment]
I tried to reproduce the error, but (unfortunately) it worked for me...
Is that`partialUpdateCompanyMembership` method called directly somewhere in your code?
Could you please post the whole stack trace of that first NPE?
The interface definitions reside in a separate Maven module and the actual implementations in another, right?

I was also getting the `StackOverflowError` because of the `JsonNode` (this is the one from Jackson, right?), I'm already working on the underlying type system for the analyzer to improve / prevent those situations ;-)

**Comment by sdaschner** [comment]
Update: The `StackOverflowError` has been fixed in 9caf038. This is included in the latest snapshot version `0.7-SNAPSHOT` which can be tested by including the Sonatype Snapshot repository:

```
<pluginRepositories>
    <pluginRepository>
        <id>ossrh-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
```
