### ISSUE TITLE
javassist.NotFoundException: T

### ISSUE THREAD

**Issue by jeff9finger** [sdaschner/jaxrs-analyzer#31]
I am using the 0.8 version. And consistently getting the above as the root cause.

We are using lots of generics in our implementation. I can send the complete maven log if that would be helpful.

Here is a sample stack trace:

[ERROR] Could not analyze the method: javassist.CtMethod@67d1e6bb[public updateOrganization (Lcom/gotransverse/tract/api/dto/party/OrganizationDTO;Ljava/lang/String;)Ljavax/ws/rs/core/Response;]
[DEBUG] java.lang.RuntimeException: java.lang.RuntimeException: javassist.NotFoundException: T
        at com.sebastian_daschner.jaxrs_analyzer.model.types.Type.<init>(Type.java:66)
        at com.sebastian_daschner.jaxrs_analyzer.model.types.Type.<init>(Type.java:49)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.LoadStoreInstructionBuilder.getType(LoadStoreInstructionBuilder.java:117)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.LoadStoreInstructionBuilder.lambda$buildVariableTypes$146(LoadStoreInstructionBuilder.java:86)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.LoadStoreInstructionBuilder.buildVariableTypes(LoadStoreInstructionBuilder.java:86)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.LoadStoreInstructionBuilder.<init>(LoadStoreInstructionBuilder.java:51)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.LoadStoreInstructionBuilder.buildVariableTypes(LoadStoreInstructionBuilder.java:86)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.LoadStoreInstructionBuilder.<init>(LoadStoreInstructionBuilder.java:51)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.ByteCodeCollector.initializeBuilders(ByteCodeCollector.java:96)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.ByteCodeCollector.buildInstructions(ByteCodeCollector.java:59)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodContentAnalyzer.interpretRelevantInstructions(MethodContentAnalyzer.java:58)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodContentAnalyzer.addProjectMethods(MethodContentAnalyzer.java:113)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodContentAnalyzer.findProjectMethods(MethodContentAnalyzer.java:88)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.ResourceMethodContentAnalyzer.analyze(ResourceMethodContentAnalyzer.java:63)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodAnalyzer.analyzeMethodContent(MethodAnalyzer.java:236)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodAnalyzer.analyzeInternal(MethodAnalyzer.java:157)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodAnalyzer.analyze(MethodAnalyzer.java:78)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.classes.ClassAnalyzer.analyzeInternal(ClassAnalyzer.java:121)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.classes.ClassAnalyzer.analyze(ClassAnalyzer.java:65)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:84)
        at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:69)
        at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo.execute(JAXRSAnalyzerMojo.java:151)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: javassist.NotFoundException: T
        at com.sebastian_daschner.jaxrs_analyzer.model.types.Type.<init>(Type.java:35)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.sebastian_daschner.jaxrs_analyzer.model.types.TypeExtractor.toTypeParameters(TypeExtractor.java:52)
        at com.sebastian_daschner.jaxrs_analyzer.model.types.Type.<init>(Type.java:64)
        ... 58 more
Caused by: javassist.NotFoundException: T
        at javassist.ClassPool.get(ClassPool.java:450)
        at com.sebastian_daschner.jaxrs_analyzer.model.types.TypeExtractor.toErasuredClass(TypeExtractor.java:39)
        at com.sebastian_daschner.jaxrs_analyzer.model.types.Type.<init>(Type.java:32)
        ... 67 more

**Comment by VladRassokhin** [comment]
Looks like same cause as in #30

**Comment by jeff9finger** [comment]
Yes, this is the same issue as #30
