### ISSUE TITLE
java.lang.RuntimeException: javassist.NotFoundException with GSON library

### ISSUE THREAD

**Issue by jordicapde** [sdaschner/jaxrs-analyzer#61]
I discovered _jaxrs-analyzer_ a few days ago and I would like to use it to generate Swagger documentation, but I am having problems with the analysis of some of my methods.
The problems come from the use of GSON library. For example, given a method like the following:
`@GET`
`@Produces("application/json")`
`public Response getBy(@PathParam("id") Long id) {`
	
	MyPOJO myPOJO = searchByID(id);
	Gson gson = new Gson();
	String response = gson.toJson(myPOJO).toString();
	
	return Response.status(200).entity(response).build();
`}`

**I run the _jaxrs-analyzer_ via standalone .jar** in debug mode and I get the following error:

`Could not analyze the method: javassist.CtMethod@b01d13ef[public getBy (Ljava/lang/Long;)Ljavax/ws/rs/core/Response;]
java.lang.RuntimeException: javassist.NotFoundException: com.google.gson.Gson
        at com.sebastian_daschner.jaxrs_analyzer.model.types.Type.<init>(Type.java:69)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.LoadStoreInstructionBuilder.getType(LoadStoreInstructionBuilder.java:101)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.LoadStoreInstructionBuilder.lambda$buildVariableTypes$4(LoadStoreInstructionBuilder.java:85)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.IntPipeline$Head.forEach(Unknown Source)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.LoadStoreInstructionBuilder.buildVariableTypes(LoadStoreInstructionBuilder.java:85)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.LoadStoreInstructionBuilder.<init>(LoadStoreInstructionBuilder.java:52)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.ByteCodeCollector.initializeBuilders(ByteCodeCollector.java:96)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.ByteCodeCollector.buildInstructions(ByteCodeCollector.java:59)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodContentAnalyzer.interpretRelevantInstructions(MethodContentAnalyzer.java:58)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.ResourceMethodContentAnalyzer.analyze(ResourceMethodContentAnalyzer.java:60)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodAnalyzer.analyzeMethodContent(MethodAnalyzer.java:236)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodAnalyzer.analyzeInternal(MethodAnalyzer.java:157)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodAnalyzer.analyze(MethodAnalyzer.java:78)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.classes.ClassAnalyzer.analyzeInternal(ClassAnalyzer.java:121)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.classes.ClassAnalyzer.analyze(ClassAnalyzer.java:65)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:84)
        at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:69)
        at com.sebastian_daschner.jaxrs_analyzer.Main.main(Main.java:131)
Caused by: javassist.NotFoundException: com.google.gson.Gson
        at javassist.ClassPool.get(ClassPool.java:450)
        at com.sebastian_daschner.jaxrs_analyzer.model.types.TypeExtractor.toErasuredClass(TypeExtractor.java:39)
        at com.sebastian_daschner.jaxrs_analyzer.model.types.Type.<init>(Type.java:66)
        ... 33 more`

Is it possible for the analyzer to work with Responses involving GSON library or am I missing something?

Thanks in advance.

**Comment by sdaschner** [comment]
I see, will check as soon as my time allows it. Did you include Gson as compile time or provided dependency?

However, I'm currently updating the internals to use ASM (instead of Javassist), can I ask you to test your project against the latest `0.10-SNAPSHOT` version? You'll need to include the maven central snapshot repositories for that.

**Comment by jordicapde** [comment]
I have added Gson in my pom.xml in the following way:
`<dependency>`
	`<groupId>com.google.code.gson</groupId>`
	`<artifactId>gson</artifactId>`
	`<version>2.6.2</version>`
`</dependency>`

And on the other hand, it would be a pleasure to give a try to the `0.10-SNAPSHOT` version. Where can I find it?

**Comment by sdaschner** [comment]
Ok, will check that later.

You can use the snapshot version by adding
```
<pluginRepositories>
	<pluginRepository>
		<id>ossrh-snapshots</id>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		<releases>
			<enabled>false</enabled>
		</releases>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</pluginRepository>
</pluginRepositories>
```

to your pom.xml. Then simply use the `0.10-SNAPSHOT` version in your `<plugin>` definition.

**Comment by sdaschner** [comment]
Sorry, now I realized you're running the Analyzer as standalone jar.

Therefore you have to configure all needed dependencies as classpath arguments, in this case Gson. This may look like:
```
java -jar jaxrs-analyzer.jar -cp ~/.m2/repository/com/google/code/gson/gson/2.6.2/gson-2.6.2.jar target/classes/
```

You can test the latest SNAPSHOT standalone version by downloading the latest jar file from https://oss.sonatype.org/content/repositories/snapshots/com/sebastian-daschner/jaxrs-analyzer/0.10-SNAPSHOT/

**Comment by jordicapde** [comment]
Thanks Sebastian,
with the SNAPSHOT version, the analyzer works fine and generates the output.

Thank you for your time!
