### ISSUE TITLE
[master] ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by essagl** [sdaschner/jaxrs-analyzer#67]
I tried to generate the swagger.json with swagger annotations for restful servicves in a tomee jax-rs application. While version 0.9 is running fine but lacks the support for swagger annotations the 0.10-SNAPSHOT version produces the following error (even without any swagger dependencies or annotations):

[ERROR] Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs (default) on project dashboard-rest: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs failed: -1 -> [Help 1]
.....
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:418)
        at java.util.ArrayList.get(ArrayList.java:431)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.classes.ProjectMethodVisitor.visitVarInsn(ProjectMethodVisitor.java:123)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.MethodContentAnalyzer.visitProjectMethod(MethodContentAnalyzer.java:122)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.MethodContentAnalyzer.addProjectMethods(MethodContentAnalyzer.java:104)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.MethodContentAnalyzer.addProjectMethods(MethodContentAnalyzer.java:111)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.MethodContentAnalyzer.findProjectMethods(MethodContentAnalyzer.java:87)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.ResourceMethodContentAnalyzer.analyze(ResourceMethodContentAnalyzer.java:58)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer.analyzeBytecode(BytecodeAnalyzer.java:26)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer$$Lambda$136/1874842251.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer.analyzeBytecode(BytecodeAnalyzer.java:18)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:100)
        at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:64)
        at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo.execute(JAXRSAnalyzerMojo.java:165)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
        ... 20 more
[ERROR]

**Comment by sdaschner** [comment]
Oh, his actually shouldn't have happened :-)

This has something to do with the structure of the Bytecode which I'm currently relying on. Will fix that.

Just for clarification, could you send me a snippet of the code which produced that error? Maybe you have the chance to restrict it to reproduce the error...

**Comment by sdaschner** [comment]
(Hopefully) fixed, didn't update the Maven snapshot yet, so you kindly can tell me the root cause source code :-)

**Comment by essagl** [comment]
Hi,
tried once more with updated sources and default configuration. Finished with UnsupportedOperationException. Here is the complete maven debug log:

[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] 
[INFO] --- jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs (default) @ dashboard-rest ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=3, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=3, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=0, ConflictResolver.conflictItemCount=3, DefaultDependencyCollector.collectTime=9, DefaultDependencyCollector.transformTime=0}
[DEBUG] com.sebastian-daschner:jaxrs-analyzer-maven-plugin:jar:0.10-SNAPSHOT:
[DEBUG]    com.sebastian-daschner:jaxrs-analyzer:jar:0.10-SNAPSHOT:compile
[DEBUG]    org.eclipse.aether:aether-api:jar:1.0.2.v20150114:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:1.1:runtime
[DEBUG] Created new class realm plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT
[DEBUG] Importing foreign packages into class realm plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT
[DEBUG]   Included: com.sebastian-daschner:jaxrs-analyzer-maven-plugin:jar:0.10-SNAPSHOT
[DEBUG]   Included: com.sebastian-daschner:jaxrs-analyzer:jar:0.10-SNAPSHOT
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.1
[DEBUG]   Excluded: org.eclipse.aether:aether-api:jar:1.0.2.v20150114
[DEBUG] Configuring mojo com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs from plugin realm ClassRealm[plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@4e25154f]
[DEBUG] Configuring mojo 'com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs' with basic configurator -->
[DEBUG]   (f) backend = plaintext
[DEBUG]   (f) buildDirectory = /home/ulrich/git/dashboard/eq-dashboard/dashboard-rest/target
[DEBUG]   (f) deployedDomain = example.com
[DEBUG]   (f) outputDirectory = /home/ulrich/git/dashboard/eq-dashboard/dashboard-rest/target/classes
[DEBUG]   (f) project = MavenProject: eq.dashboard:dashboard-rest:1.0-SNAPSHOT @ /home/ulrich/git/dashboard/eq-dashboard/dashboard-rest/pom.xml
[DEBUG]   (f) remoteRepos = [central (http://repo.maven.apache.org/maven2, releases)]
[DEBUG]   (f) renderSwaggerTags = false
[DEBUG]   (f) repoSession = org.eclipse.aether.DefaultRepositorySystemSession@478fe415
[DEBUG]   (f) swaggerSchemes = [http]
[DEBUG]   (f) swaggerTagsPathOffset = 0
[DEBUG] -- end configuration --
[INFO] analyzing JAX-RS resources, using Plain text backend
[DEBUG] Resolving artifact javax:javaee-api:jar:7.0 from [central (http://repo.maven.apache.org/maven2, releases)]
[DEBUG] Resolved artifact javax:javaee-api:jar:7.0 to /data/.m2/repository/javax/javaee-api/7.0/javaee-api-7.0.jar from central (http://repo.maven.apache.org/maven2, releases)
[DEBUG] Dependency paths are: [/data/.m2/repository/org/apache/openwebbeans/openwebbeans-el22/1.2.7/openwebbeans-el22-1.2.7.jar, /data/.m2/repository/org/apache/openwebbeans/openwebbeans-web/1.2.7/openwebbeans-web-1.2.7.jar, /data/.m2/repository/javax/mail/mail/1.4.5/mail-1.4.5.jar, /data/.m2/repository/org/apache/cxf/cxf-rt-rs-security-cors/2.6.16/cxf-rt-rs-security-cors-2.6.16.jar, /data/.m2/repository/org/apache/xbean/xbean-naming/4.2/xbean-naming-4.2.jar, /data/.m2/repository/org/apache/openejb/mbean-annotation-api/4.7.3/mbean-annotation-api-4.7.3.jar, /data/.m2/repository/org/apache/activemq/activemq-jdbc-store/5.10.2/activemq-jdbc-store-5.10.2.jar, /data/.m2/repository/org/apache/activemq/activemq-kahadb-store/5.10.2/activemq-kahadb-store-5.10.2.jar, /data/.m2/repository/org/apache/openejb/openejb-server/4.7.3/openejb-server-4.7.3.jar, /data/.m2/repository/org/apache/openejb/openejb-jee/4.7.3/openejb-jee-4.7.3.jar, /data/.m2/repository/org/slf4j/slf4j-jdk14/1.7.7/slf4j-jdk14-1.7.7.jar, /data/.m2/repository/org/apache/geronimo/javamail/geronimo-javamail_1.4_mail/1.9.0-alpha-2/geronimo-javamail_1.4_mail-1.9.0-alpha-2.jar, /data/.m2/repository/org/apache/xbean/xbean-finder-shaded/4.2/xbean-finder-shaded-4.2.jar, /data/.m2/repository/org/codehaus/jettison/jettison/1.3.4/jettison-1.3.4.jar, /data/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar, /data/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar, /data/.m2/repository/org/apache/activemq/activemq-client/5.10.2/activemq-client-5.10.2.jar, /data/.m2/repository/org/metatype/sxc/sxc-runtime/0.8/sxc-runtime-0.8.jar, /data/.m2/repository/org/apache/openejb/openejb-cxf-transport/4.7.3/openejb-cxf-transport-4.7.3.jar, /data/.m2/repository/org/apache/openejb/openejb-rest/4.7.3/openejb-rest-4.7.3.jar, /data/.m2/repository/org/apache/openejb/openejb-jee-accessors/4.7.3/openejb-jee-accessors-4.7.3.jar, /data/.m2/repository/org/metatype/sxc/sxc-jaxb-core/0.8/sxc-jaxb-core-0.8.jar, /data/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar, /data/.m2/repository/org/apache/xbean/xbean-asm5-shaded/4.2/xbean-asm5-shaded-4.2.jar, /data/.m2/repository/org/apache/openwebbeans/openwebbeans-spi/1.2.7/openwebbeans-spi-1.2.7.jar, /data/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar, /data/.m2/repository/org/apache/ws/xmlschema/xmlschema-core/2.0.3/xmlschema-core-2.0.3.jar, /data/.m2/repository/net/sourceforge/serp/serp/1.15.1/serp-1.15.1.jar, /data/.m2/repository/org/apache/openwebbeans/openwebbeans-ee-common/1.2.7/openwebbeans-ee-common-1.2.7.jar, /data/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar, /data/.m2/repository/org/apache/cxf/cxf-rt-transports-http/2.6.16/cxf-rt-transports-http-2.6.16.jar, /data/.m2/repository/org/codehaus/woodstox/woodstox-core-asl/4.4.0/woodstox-core-asl-4.4.0.jar, /data/.m2/repository/org/apache/cxf/cxf-rt-rs-extension-providers/2.6.16/cxf-rt-rs-extension-providers-2.6.16.jar, /data/.m2/repository/org/apache/geronimo/components/geronimo-transaction/3.1.1/geronimo-transaction-3.1.1.jar, /data/.m2/repository/org/objectweb/howl/howl/1.0.1-1/howl-1.0.1-1.jar, /data/.m2/repository/org/apache/cxf/cxf-rt-rs-security-oauth2/2.6.16/cxf-rt-rs-security-oauth2-2.6.16.jar, /data/.m2/repository/javax/javaee-api/7.0/javaee-api-7.0.jar, /data/.m2/repository/org/fusesource/hawtbuf/hawtbuf/1.10/hawtbuf-1.10.jar, /data/.m2/repository/org/codehaus/swizzle/swizzle-stream/1.6.2/swizzle-stream-1.6.2.jar, /data/.m2/repository/org/apache/openjpa/openjpa/2.4.0/openjpa-2.4.0.jar, /data/.m2/repository/org/apache/cxf/cxf-rt-frontend-jaxrs/2.6.16/cxf-rt-frontend-jaxrs-2.6.16.jar, /data/.m2/repository/org/hsqldb/hsqldb/2.3.2/hsqldb-2.3.2.jar, /data/.m2/repository/javax/enterprise/concurrent/javax.enterprise.concurrent-api/1.0/javax.enterprise.concurrent-api-1.0.jar, /data/.m2/repository/org/apache/geronimo/specs/geronimo-j2ee-connector_1.6_spec/1.0/geronimo-j2ee-connector_1.6_spec-1.0.jar, /data/.m2/repository/org/apache/commons/commons-email/1.3.3/commons-email-1.3.3.jar, /data/.m2/repository/net/sf/supercsv/super-csv/2.2.0/super-csv-2.2.0.jar, /data/.m2/repository/org/apache/openejb/openejb-javaagent/4.7.3/openejb-javaagent-4.7.3.jar, /data/.m2/repository/org/apache/cxf/cxf-api/2.6.16/cxf-api-2.6.16.jar, /data/.m2/repository/org/apache/openejb/openejb-core/4.7.3/openejb-core-4.7.3.jar, /data/.m2/repository/org/apache/openejb/openejb-jpa-integration/4.7.3/openejb-jpa-integration-4.7.3.jar, /data/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar, /data/.m2/repository/org/apache/xbean/xbean-bundleutils/4.2/xbean-bundleutils-4.2.jar, /data/.m2/repository/mysql/mysql-connector-java/5.1.38/mysql-connector-java-5.1.38.jar, /data/.m2/repository/org/apache/xbean/xbean-reflect/4.2/xbean-reflect-4.2.jar, /data/.m2/repository/eq/dashboard/dashboard-core/1.0-SNAPSHOT/dashboard-core-1.0-SNAPSHOT.jar, /data/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar, /data/.m2/repository/org/apache/openwebbeans/openwebbeans-impl/1.2.7/openwebbeans-impl-1.2.7.jar, /data/.m2/repository/org/apache/bval/bval-core/0.5/bval-core-0.5.jar, /data/.m2/repository/org/apache/openejb/openejb-ejbd/4.7.3/openejb-ejbd-4.7.3.jar, /data/.m2/repository/org/fusesource/jansi/jansi/1.8/jansi-1.8.jar, /data/.m2/repository/org/apache/activemq/activemq-ra/5.10.2/activemq-ra-5.10.2.jar, /data/.m2/repository/com/quipex/quipex-utils/0.0.1-SNAPSHOT/quipex-utils-0.0.1-SNAPSHOT.jar, /data/.m2/repository/org/apache/openejb/openejb-concurrency-utilities-ee/4.7.3/openejb-concurrency-utilities-ee-4.7.3.jar, /data/.m2/repository/org/apache/openwebbeans/openwebbeans-ee/1.2.7/openwebbeans-ee-1.2.7.jar, /data/.m2/repository/commons-beanutils/commons-beanutils-core/1.8.3/commons-beanutils-core-1.8.3.jar, /data/.m2/repository/org/apache/cxf/cxf-rt-core/2.6.16/cxf-rt-core-2.6.16.jar, /data/.m2/repository/org/apache/geronimo/components/geronimo-connector/3.1.1/geronimo-connector-3.1.1.jar, /data/.m2/repository/org/apache/commons/commons-lang3/3.3.1/commons-lang3-3.3.1.jar, /data/.m2/repository/org/apache/openejb/openejb-cxf-rs/4.7.3/openejb-cxf-rs-4.7.3.jar, /data/.m2/repository/org/apache/openejb/openejb-http/4.7.3/openejb-http-4.7.3.jar, /data/.m2/repository/org/apache/bval/bval-jsr303/0.5/bval-jsr303-0.5.jar, /data/.m2/repository/org/apache/activemq/activemq-broker/5.10.2/activemq-broker-5.10.2.jar, /data/.m2/repository/com/sun/xml/bind/jaxb-impl/2.1.13/jaxb-impl-2.1.13.jar, /data/.m2/repository/org/apache/activemq/activemq-openwire-legacy/5.10.2/activemq-openwire-legacy-5.10.2.jar, /data/.m2/repository/org/apache/openejb/openejb-loader/4.7.3/openejb-loader-4.7.3.jar, /data/.m2/repository/org/apache/cxf/cxf-rt-rs-extension-search/2.6.16/cxf-rt-rs-extension-search-2.6.16.jar, /data/.m2/repository/org/apache/openejb/openejb-client/4.7.3/openejb-client-4.7.3.jar, /data/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar, /data/.m2/repository/org/apache/openejb/shade/quartz-openejb-shade/2.2.1/quartz-openejb-shade-2.2.1.jar, /data/.m2/repository/org/apache/cxf/cxf-rt-bindings-xml/2.6.16/cxf-rt-bindings-xml-2.6.16.jar, /data/.m2/repository/eq/dashboard/dashboard-quoter/1.0-SNAPSHOT/dashboard-quoter-1.0-SNAPSHOT.jar, /data/.m2/repository/org/apache/cxf/cxf-rt-management/2.6.16/cxf-rt-management-2.6.16.jar, /data/.m2/repository/org/apache/openejb/javaee-api/6.0-6/javaee-api-6.0-6.jar, /data/.m2/repository/javax/activation/activation/1.1.1/activation-1.1.1.jar, /data/.m2/repository/commons-pool/commons-pool/1.5.7/commons-pool-1.5.7.jar, /data/.m2/repository/org/apache/activemq/protobuf/activemq-protobuf/1.1/activemq-protobuf-1.1.jar, /data/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar, /data/.m2/repository/org/apache/openejb/openejb-api/4.7.3/openejb-api-4.7.3.jar, /data/.m2/repository/org/apache/openwebbeans/openwebbeans-ejb/1.2.7/openwebbeans-ejb-1.2.7.jar, /data/.m2/repository/commons-dbcp/commons-dbcp/1.4/commons-dbcp-1.4.jar]
[DEBUG] Project paths are: [/home/ulrich/git/dashboard/eq-dashboard/dashboard-rest/target/classes]
[DEBUG] Annotation not handled: Ljavax/ejb/EJB;
[DEBUG] Annotation not handled: Ljavax/ejb/EJB;
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.799 s
[INFO] Finished at: 2016-07-25T20:31:50+01:00
[INFO] Final Memory: 27M/423M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs (default) on project dashboard-rest: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs failed. UnsupportedOperationException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs (default) on project dashboard-rest: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10-SNAPSHOT:analyze-jaxrs failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableCollection.add(Collections.java:1055)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulate(MethodSimulator.java:110)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator$$Lambda$186/139374530.accept(Unknown Source)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInternal(MethodSimulator.java:73)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.InjectableArgumentMethodSimulator.simulate(InjectableArgumentMethodSimulator.java:63)
        at com.sebastian_daschner.jaxrs_analyzer.model.methods.ProjectMethod.invoke(ProjectMethod.java:47)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInvoke(MethodSimulator.java:181)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulate(MethodSimulator.java:93)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator$$Lambda$186/139374530.accept(Unknown Source)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInternal(MethodSimulator.java:73)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.InjectableArgumentMethodSimulator.simulate(InjectableArgumentMethodSimulator.java:63)
        at com.sebastian_daschner.jaxrs_analyzer.model.methods.ProjectMethod.invoke(ProjectMethod.java:47)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInvoke(MethodSimulator.java:181)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulate(MethodSimulator.java:93)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator$$Lambda$186/139374530.accept(Unknown Source)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInternal(MethodSimulator.java:73)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.InjectableArgumentMethodSimulator.simulate(InjectableArgumentMethodSimulator.java:63)
        at com.sebastian_daschner.jaxrs_analyzer.model.methods.ProjectMethod.invoke(ProjectMethod.java:47)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInvoke(MethodSimulator.java:181)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulate(MethodSimulator.java:93)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator$$Lambda$186/139374530.accept(Unknown Source)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInternal(MethodSimulator.java:73)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulate(MethodSimulator.java:60)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.ResourceMethodContentAnalyzer.analyze(ResourceMethodContentAnalyzer.java:63)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer.analyzeBytecode(BytecodeAnalyzer.java:26)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer$$Lambda$136/1268591854.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer.analyzeBytecode(BytecodeAnalyzer.java:18)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:100)
        at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:64)
        at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo.execute(JAXRSAnalyzerMojo.java:165)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
        ... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
ulrich@ulrich-nb:~/git/dashboard/eq-dashboard/dashboard-rest$

**Comment by sdaschner** [comment]
This error should also now be fixed. I deployed the new `SNAPSHOT` version. Would you mind trying it again?

**Comment by essagl** [comment]
Ok - i found the time to pull your commits and build the source.
Now on my tomee project the following exception is thrown when running the maven build.
I attached the file, so you can see all used dependencies.
[jaxrs-analyser-exception-log.txt](https://github.com/sdaschner/jaxrs-analyzer/files/427581/jaxrs-analyser-exception-log.txt)

**Comment by sdaschner** [comment]
Sorry for the late response!
Well, that seems like a Bytecode incompatibility error, but still that's somehow strange... I'll try to dive more into that as soon as I have the time.

Maybe you can try to add the Java EE 7 API (javax:javaee-api:7.0) and to temporarily replace the OpenEJB dependencies?
