### ISSUE TITLE
Does not supports java version 1.7

### ISSUE THREAD

**Issue by jocnud** [sdaschner/jaxrs-analyzer#68]
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/sebastian_daschner/jaxrs_analyzer/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by sdaschner** [comment]
Yes, to run the analyzer you'll need Java 8. I'm relying to heavily on JDK 1.8 features internally.
