### ISSUE TITLE
Exception thrown when building with Maven

### ISSUE THREAD

**Issue by kukudas** [sdaschner/jaxrs-analyzer#71]
Hi,
when i execute the following maven command: mvn clean install -X i get the following failure:

`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.9:analyze-jaxrs (default) on project: E
xecution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.9:analyze-jaxrs failed: Unable to load the mojo 'analyze-jaxrs' (or one of its required components) from the plugin 'com.s
ebastian-daschner:jaxrs-analyzer-maven-plugin:0.9'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.9:analyze-jaxrs failed: Unable to load the mojo 'analyze-jax
rs' (or one of its required components) from the plugin 'com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.9'
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'analyze-jaxrs' (or one of its required components) from the plugin 'com.sebastian-daschner:jaxrs-analyzer-maven-pl
ugin:0.9'
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:488)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
        ... 20 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.eclipse.aether.RepositorySystem was bound.
  while locating com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo
  at ClassRealm[plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.9, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
  while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.9:analyze-jaxrs)

1 error
      role: org.apache.maven.plugin.Mojo
  roleHint: com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.9:analyze-jaxrs
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:257)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
        ... 21 more
Caused by: com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.eclipse.aether.RepositorySystem was bound.
  while locating com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo
  at ClassRealm[plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.9, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
  while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.9:analyze-jaxrs)

1 error
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:974)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
        ... 23 more`

Any idears?

**Comment by sdaschner** [comment]
Sorry for the late response.
Looks like a Maven version problem. Which version of Maven are you using?

**Comment by marcelcamporelli** [comment]
Hi guys, I had the same problem - and Sebastian was right.
Most linux distributions do not come with the latest Maven version installed, typically with 3.0.4 or 3.0.5. After installing 3.3.9, it actually worked fine for me.

**Comment by sdaschner** [comment]
Thanks for confirming -- closing for now. Feel free to re-open if the problem persists.

**Comment by t-shaguy** [comment]
Yes, many thanks to @sdaschner and all, upgrading to 3.3.9 worked.
