### ISSUE TITLE
Execution fails for 0.10 if "genson" is a dependency

### ISSUE THREAD

**Issue by simdevmon** [sdaschner/jaxrs-analyzer#74]
The execution of jaxrs-analyzer fails, if genson is used as a dependency in the project. 

```
        <dependency>
            <groupId>com.owlike</groupId>
            <artifactId>genson</artifactId>
            <version>1.4</version>
        </dependency>
```

It will produce the following error:

```
Exception in thread "main" java.util.ServiceConfigurationError: javax.json.spi.JsonProvider: Provider com.owlike.genson.ext.jsr353.GensonJsonProvider not a subtype
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at javax.json.spi.JsonProvider.provider(JsonProvider.java:90)
    at javax.json.Json.createObjectBuilder(Json.java:266)
    at com.sebastian_daschner.jaxrs_analyzer.backend.swagger.SwaggerBackend.render(SwaggerBackend.java:66)
    at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:72)
    at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo.execute(JAXRSAnalyzerMojo.java:165)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

It works fine with jaxrs-analyzer 0.9 or with 0.10, if genson is removed. I verified this with an empty project.

**Comment by sdaschner** [comment]
Hmm, yes the dependency resolution for the maven plugin is still a bit tricky...

Could you please re-check with the `0.11-SNAPSHOT` version of the Maven plugin? If that doesn't help, then I'll guess we need to write an own class loading mechanism.

**Comment by simdevmon** [comment]
I could not find the `0.11-SNAPSHOT` version on Maven Central. Is there any special repository for snapshots?

**Comment by sdaschner** [comment]
Oh yes, sorry for not mentioning it. The snapshot dependencies are only available in the snapshot repository of Maven central.

You have to add the following to your `pom.xml`:

```
<pluginRepositories>
	<pluginRepository>
		<id>ossrh-snapshots</id>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		<releases>
			<enabled>false</enabled>
		</releases>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</pluginRepository>
</pluginRepositories>
```

**Comment by simdevmon** [comment]
Thank you, I just tried it again with `0.11-SNAPSHOT`, but I still get the same error message.

**Comment by sdaschner** [comment]
Ok, the Analyzer seems to use Genson as implementation at analysis time, which we don't want. Probably we have to write an own class loading mechanism...

Thanks for submitting, I hope we get going with that soon.

**Comment by simdevmon** [comment]
Works with 0.15
