### ISSUE TITLE
Resolve local variables scopes correctly

### ISSUE THREAD

**Issue by fkleon** [sdaschner/jaxrs-analyzer#80]
Here are minimal failing and working examples: https://gist.github.com/fkleon/0b1f0ba089a33cd3c02d55f80da0424a

In this example, when simulating the call `.type(contentType)` the `runtimeStack` of `MethodSimulator` contains the wrong top element which is then selected as argument to the method.
The top element on the stack is still an integer left over from the previous variable assignment from within the for loop (`int i = 0`), while it should be a `null` value from the next assignment after the for loop.

The failing example does simulate the method call with this argument whose value cannot be cast to String:
`[Element{possibleValues=[0], types='[Ljava/lang/String;, Ljava/lang/Object;, I]'}]`

The working example does correctly simulate the call with an empty value:
`[Element{possibleValues=[], types='[Ljava/lang/String;, Ljava/lang/Object;]'}]`

This seems to only happen after a variable declaration and assignment at the same time within a for loop, and as you can see from the second example a simple workaround is declaring the variable before using it in the for loop.

However the error message is not very helpful and debugging this issue requires some understanding of the simulation methods and extensive digging.

Full stack trace:
<pre>
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.KnownResponseResultMethod.lambda$92(KnownResponseResultMethod.java:134)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.KnownResponseResultMethod.lambda$21(KnownResponseResultMethod.java:134)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.KnownResponseResultMethod.invoke(KnownResponseResultMethod.java:430)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInvoke(MethodSimulator.java:181)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulate(MethodSimulator.java:93)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInternal(MethodSimulator.java:73)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulate(MethodSimulator.java:60)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.ResourceMethodContentAnalyzer.analyze(ResourceMethodContentAnalyzer.java:63)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer.analyzeBytecode(BytecodeAnalyzer.java:26)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer.analyzeBytecode(BytecodeAnalyzer.java:18)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:104)
	at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:68)
	at com.sebastian_daschner.jaxrs_analyzer.Main.main(Main.java:99)
</pre>

**Comment by sdaschner** [comment]
Oh yes, that's a hidden and nasty one... The problem is that for now the resolution of local variables is not fully correct, the analysis should take scopes into account which isn't fully implemented for some corner cases. The reason why declaring the variable before the loop makes it available in the same scope as the `contentType` variable in your scenario and then there's no clash with the second variable anymore.
Take a look at the bytecode of your two methods if you want, you will see that the local variables have both index `1` (with a different scope, of course), that causes currently the clash.

Thanks a lot for finding and submitting!
