### ISSUE TITLE
Javadoc Error

### ISSUE THREAD

**Issue by oluwasayo** [sdaschner/jaxrs-analyzer#83]
Javadoc comment not showing in generated docs. 

The following error is logged on console even though the said method is present.
`javadoc: error - Doclet class com.sebastian_daschner.jaxrs_analyzer.analysis.javadoc.JAXRSDoclet does not contain a start method`

**Comment by sdaschner** [comment]
Yes, I'm on it. The problem is that version `0.11` and the contained mechanism is broken. I'm done working around that problem and will publish a new version very soonish. Will let you know.

Thanks for trying that out!

**Comment by oluwasayo** [comment]
I'll keep building against master until it works. It's actually kind of critical that I get this working in my app. I've tried messing around with the source seeing if I could fix it myself but I couldn't. Thanks a lot!

**Comment by sdaschner** [comment]
Yes, as it turns out, Maven central has huge problems syncing the repos today... Otherwise version `0.12` would already be avaliable... Sometimes it happens all at once ;-)

**Comment by oluwasayo** [comment]
So I've pulled the 0.13-SNAPSHOT, and changed the version to 0.11 then built/installed skipping tests (one failing test, not sure if it's the same on your end). But then, building from the Maven plugin (using the new local 0.11 which is essentially 0.13-SNAPSHOT), it logs an error.

`[ERROR] could not analyze JavaDoc, reason: com.sebastian_daschner.jaxrs_analyzer.analysis.javadoc.JAXRSDoclet
[DEBUG] java.lang.ClassNotFoundException: com.sebastian_daschner.jaxrs_analyzer.analysis.javadoc.JAXRSDoclet
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.javadoc.JavaDocAnalyzer.invokeDoclet(JavaDocAnalyzer.java:40)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.javadoc.JavaDocAnalyzer.analyze(JavaDocAnalyzer.java:30)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:108)
        at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:69)
        at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo.execute(JAXRSAnalyzerMojo.java:177)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)`

I unpacked the shaded JAR and the class is in there.

**Comment by sdaschner** [comment]
Yes, there was a version mismatch the whole day due to issues w/ Maven central. Could you please retry using the `0.13-SNAPSHOT` version? The `0.12` should be synced soonish as well...
