### ISSUE TITLE
ClassNotFoundException  com.sebastian_daschner.jaxrs_analyzer.backend.Backend

### ISSUE THREAD

**Issue by AlbozDroid** [sdaschner/jaxrs-analyzer#85]
Hello,

I'm trying to generate some JAX-RS 2.1  documentation. I'm using Java EE 7 and Java 8.
Here is my POM:

> <build>
        <finalName>MobileAPIDocs</finalName>
        <plugins>
            <plugin>
                <groupId>com.sebastian-daschner</groupId>
                <artifactId>jaxrs-analyzer-maven-plugin</artifactId>
                <version>0.11</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>analyze-jaxrs</goal>
                        </goals>
                        <configuration>
                            <backend>swagger</backend>                   
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

And here is the error when I run Clean and Build:

> WARNING: Error injecting: com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo
java.lang.NoClassDefFoundError: com/sebastian_daschner/jaxrs_analyzer/backend/Backend
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.getDeclaredMethods(Class.java:1967)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:664)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:358)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:155)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:542)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:528)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:833)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:758)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:255)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:204)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:954)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:987)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:950)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.ClassNotFoundException: com.sebastian_daschner.jaxrs_analyzer.backend.Backend

**Comment by sdaschner** [comment]
Hi! I don't know whether it will affect that error but the `0.11` release has a few known issues...

Could you please retry with the `0.12` version that has just been published today?

**Comment by AlbozDroid** [comment]
Hi,

I upgraded to versiob 0.12 and this is the new Exception now..

> WARNING: Error injecting: com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo
com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.eclipse.aether.RepositorySystem was bound.
  while locating com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo

1 error
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:974)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

**Comment by AlbozDroid** [comment]
The problem with version "0.12" was a maven issue. Once I upgraded to the latest maven (3.3.9) it worked like a charm.

Thanks!

**Comment by sdaschner** [comment]
Ok, thx for the info

**Comment by tedmonds-cl** [comment]
I am having the same issue. We are using maven 3.3.9

`$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /usr/share/apache-maven-3.3.9
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-91-virtual", arch: "amd64", family: "unix"`

`[artifact:mvn] [INFO] [ERROR] Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.12:analyze-jaxrs (default) on project X: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.12:analyze-jaxrs failed: Unable to load the mojo 'analyze-jaxrs' (or one of its required components) from the plugin 'com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.12': com.google.inject.ProvisionException: Guice provision errors:
[artifact:mvn] [INFO] [ERROR]
[artifact:mvn] [INFO] [ERROR] 1) No implementation for org.eclipse.aether.RepositorySystem was bound.
[artifact:mvn] [INFO] [ERROR] while locating com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo
[artifact:mvn] [INFO] [ERROR] at ClassRealm[plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.12, parent: sun.misc.Launcher$AppClassLoader@70dea4e]
[artifact:mvn] [INFO] [ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.12:analyze-jaxrs)
[artifact:mvn] [INFO] [ERROR]
[artifact:mvn] [INFO] [ERROR] 1 error
[artifact:mvn] [INFO] [ERROR] role: org.apache.maven.plugin.Mojo
[artifact:mvn] [INFO] [ERROR] roleHint: com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.12:analyze-jaxrs`

**Comment by sdaschner** [comment]
@tedmonds-cl Do you include a dependency to Guice in your project? Or what dependencies do you have beside the Java EE 7 API?

**Comment by tedmonds-cl** [comment]
No dependency on Guice.
Here are all of the dependencies:

`[INFO] The following files have been resolved:
[INFO]    org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0-b30:compile
[INFO]    net.jcip:jcip-annotations:jar:1.0:provided
[INFO]    org.javassist:javassist:jar:3.20.0-GA:compile
[INFO]    com.google.code.findbugs:findbugs:jar:3.0.1:provided
[INFO]    org.glassfish.web:javax.el:jar:2.2.4:compile
[INFO]    com.google.code.findbugs:annotations:jar:3.0.0:compile
[INFO]    com.google.guava:guava:jar:17.0:compile
[INFO]    xml-apis:xml-apis:jar:1.0.b2:compile
[INFO]    javax.el:javax.el-api:jar:3.0.0:compile
[INFO]    com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO]    antlr:antlr:jar:2.7.7:compile
[INFO]    org.glassfish.hk2:hk2-utils:jar:2.5.0-b30:compile
[INFO]    org.ow2.asm:asm:jar:5.0.2:provided
[INFO]    net.sf.jazzy:jazzy:jar:0.5.1:compile
[INFO]    com.google.code.findbugs:jFormatString:jar:2.0.1:provided
[INFO]    com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.3.2:compile
[INFO]    commons-io:commons-io:jar:2.4:compile
[INFO]    org.glassfish.jersey.core:jersey-client:jar:2.25:compile
[INFO]    com.fasterxml.jackson.core:jackson-databind:jar:2.3.2:compile
[INFO]    org.slf4j:slf4j-api:jar:1.7.5:compile
[INFO]    org.glassfish.jersey.core:jersey-server:jar:2.25:compile
[INFO]    com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.3.2:compile
[INFO]    com.sun.xml.bind:jaxb-impl:jar:2.1.7:compile
[INFO]    org.glassfish.hk2.external:javax.inject:jar:2.2.0-b14:compile
[INFO]    com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.3.2:compile
[INFO]    com.apple:AppleJavaExtensions:jar:1.4:provided
[INFO]    javax.validation:validation-api:jar:sources:1.0.0.GA:compile
[INFO]    com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.3.2:compile
[INFO]    javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO]    javax.xml.bind:jaxb-api:jar:2.1:compile
[INFO]    org.ow2.asm:asm-commons:jar:5.0.2:provided
[INFO]    org.ow2.asm:asm-tree:jar:5.0.2:provided
[INFO]    com.fasterxml.jackson.core:jackson-annotations:jar:2.3.2:compile
[INFO]    org.glassfish.jersey.core:jersey-common:jar:2.25:compile
[INFO]    com.google.code.gson:gson:jar:2.2.4:compile
[INFO]    org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO]    dom4j:dom4j:jar:1.6.1:compile
[INFO]    com.google.code.findbugs:bcel-findbugs:jar:6.0:provided
[INFO]    com.fasterxml:classmate:jar:1.0.0:compile
[INFO]    org.fusesource.restygwt:restygwt:jar:2.0.1:compile
[INFO]    org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.13:compile
[INFO]    commons-lang:commons-lang:jar:2.6:provided
[INFO]    org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
[INFO]    org.jboss:jandex:jar:1.1.0.Final:compile
[INFO]    org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.25:compile
[INFO]    javax.activation:activation:jar:1.1:compile
[INFO]    javax.ws.rs:javax.ws.rs-api:jar:2.0:compile
[INFO]    org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO]    org.glassfish.jersey.media:jersey-media-jaxb:jar:2.25:compile
[INFO]    org.hibernate:hibernate-validator:jar:5.1.3.Final:compile
[INFO]    tablelayout:TableLayout:jar:20050920:compile
[INFO]    javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO]    org.hibernate:hibernate-core:jar:4.3.8.Final:compile
[INFO]    org.hibernate.common:hibernate-commons-annotations:jar:4.0.5.Final:compile
[INFO]    org.glassfish.hk2:hk2-api:jar:2.5.0-b30:compile
[INFO]    org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO]    org.ow2.asm:asm-debug-all:jar:5.0.2:provided
[INFO]    org.hibernate:hibernate-entitymanager:jar:4.3.8.Final:compile
[INFO]    org.jboss.logging:jboss-logging-annotations:jar:1.2.0.Beta1:compile
[INFO]    org.glassfish.hk2:hk2-locator:jar:2.5.0-b30:compile
[INFO]    org.glassfish.jersey.ext:jersey-bean-validation:jar:2.25:compile
[INFO]    com.fasterxml.jackson.core:jackson-core:jar:2.3.2:compile
[INFO]    org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.0.0.Final:compile
[INFO]    org.swinglabs.swingx:swingx-common:jar:1.6.5-1:compile
[INFO]    org.timepedia.exporter:gwtexporter:jar:2.5.1:compile
[INFO]    jaxen:jaxen:jar:1.1.6:provided`

**Comment by tedmonds-cl** [comment]
Any thoughts @sdaschner ?

**Comment by sdaschner** [comment]
Ok, probably related to #73. We try to tackle that problem soon.

**Comment by srinivas-pondugula** [comment]
Hi,

My project is having dependency on Guice and getting same error. jaxrs-analyzer will not work if we have Guice dependency?

**Comment by srinivas-pondugula** [comment]
Hi,

My project is having dependency on Guice and getting same error. jaxrs-analyzer will not work if we have Guice dependency?

**Comment by srinivas-pondugula** [comment]
Hi,
My project is having dependency on Guice and getting same error. jaxrs-analyzer will not work if we have Guice dependency?
